export const skillsConfig = [
  {
    id: "typescript",
    type: "skill",
    label: "TypeScript",
    themed: false,
  },
  {
    id: "javascript",
    type: "skill",
    label: "JavaScript",
    themed: false,
  },
  {
    id: "react-js",
    type: "skill",
    label: "React JS",
    themed: true,
  },
  {
    id: "next-js",
    type: "skill",
    label: "Next JS",
    themed: true,
  },
  {
    id: "html",
    type: "skill",
    label: "HTML",
    themed: false,
  },
  {
    id: "css",
    type: "skill",
    label: "CSS",
    themed: false,
  },
  {
    id: "tailwind-css",
    type: "skill",
    label: "Tailwind CSS",
    themed: true,
  },
  {
    id: "bootstrap",
    type: "skill",
    label: "Bootstrap",
    themed: false,
  },
  {
    id: "sass",
    type: "skill",
    label: "Sass",
    themed: false,
  },
  {
    id: "material-ui",
    type: "skill",
    label: "Material UI",
    themed: true,
  },
  {
    id: "react-router",
    type: "skill",
    label: "React Router",
    themed: true,
  },
  {
    id: "redux",
    type: "skill",
    label: "Redux",
    themed: false,
  },
  {
    id: "zustand",
    type: "skill",
    label: "Zustand",
    themed: false,
  },
  {
    id: "node-js",
    type: "skill",
    label: "Node JS",
    themed: true,
  },
  {
    id: "express-js",
    type: "skill",
    label: "Express JS",
    themed: true,
  },
  {
    id: "python",
    type: "skill",
    label: "Python",
    themed: true,
  },
  {
    id: "django",
    type: "skill",
    label: "Django",
    themed: false,
  },
  {
    id: "fast-api",
    type: "skill",
    label: "FastAPI",
    themed: false,
  },
  {
    id: "flask",
    type: "skill",
    label: "Flask",
    themed: true,
  },
  {
    id: "java",
    type: "skill",
    label: "Java",
    themed: true,
  },
  {
    id: "mongo-db",
    type: "skill",
    label: "MongoDB",
    themed: false,
  },
  {
    id: "postgre-sql",
    type: "skill",
    label: "PostgreSQL",
    themed: true,
  },
  {
    id: "my-sql",
    type: "skill",
    label: "mySQL",
    themed: true,
  },
  {
    id: "prisma",
    type: "skill",
    label: "Prisma",
    themed: false,
  },
  {
    id: "redis",
    type: "skill",
    label: "Redis",
    themed: true,
  },
  {
    id: "firebase",
    type: "skill",
    label: "Firebase",
    themed: true,
  },
  {
    id: "amazon-web-services",
    type: "skill",
    label: "Amazon Web Services",
    themed: true,
  },
  {
    id: "docker",
    type: "skill",
    label: "Docker",
    themed: false,
  },
  {
    id: "graphql",
    type: "skill",
    label: "graphql",
    themed: true,
  },
  {
    id: "git",
    type: "skill",
    label: "Git",
    themed: false,
  },
];

export const toolsConfig = [
  {
    id: "visual-studio-code",
    type: "tool",
    label: "Visual Studio Code",
    themed: true,
  },
  {
    id: "postman",
    type: "tool",
    label: "Postman",
    themed: false,
  },
  {
    id: "git-lab",
    type: "tool",
    label: "GitLab",
    themed: true,
  },
  {
    id: "github-actions",
    type: "tool",
    label: "GitHub Actions",
    themed: true,
  },
  {
    id: "bash",
    type: "tool",
    label: "Bash",
    themed: true,
  },
  {
    id: "nginx",
    type: "tool",
    label: "Nginx",
    themed: false,
  },
  {
    id: "pm2",
    type: "tool",
    label: "PM2",
    themed: false,
  },
  {
    id: "cloudflare",
    type: "tool",
    label: "Cloudflare",
    themed: true,
  },
  {
    id: "cloudinary",
    type: "tool",
    label: "Cloudinary",
    themed: false,
  },
  {
    id: "npm",
    type: "tool",
    label: "NPM",
    themed: true,
  },
  {
    id: "pnpm",
    type: "tool",
    label: "PNPM",
    themed: true,
  },
  {
    id: "yarn",
    type: "tool",
    label: "Yarn",
    themed: true,
  },
  {
    id: "webpack",
    type: "tool",
    label: "Webpack",
    themed: true,
  },
  {
    id: "vite",
    type: "tool",
    label: "Vite",
    themed: true,
  },
  {
    id: "vitest",
    type: "tool",
    label: "Vitest",
    themed: true,
  },
  {
    id: "babel",
    type: "tool",
    label: "Babel",
    themed: false,
  },
  {
    id: "vercel",
    type: "tool",
    label: "Vercel",
    themed: true,
  },
  {
    id: "netlify",
    type: "tool",
    label: "Netlify",
    themed: true,
  },
  {
    id: "jenkins",
    type: "tool",
    label: "Jenkins",
    themed: true,
  },
  {
    id: "grafana",
    type: "tool",
    label: "Grafana",
    themed: true,
  },
  {
    id: "sentry",
    type: "tool",
    label: "Sentry",
    themed: false,
  },
  {
    id: "visual-studio",
    type: "tool",
    label: "Visual Studio",
    themed: true,
  },
  {
    id: "intellij-idea",
    type: "tool",
    label: "IntelliJ Idea",
    themed: true,
  },
  {
    id: "pycharm",
    type: "tool",
    label: "PyCharm",
    themed: true,
  },
  {
    id: "ubuntu",
    type: "tool",
    label: "Ubuntu",
    themed: true,
  },
  {
    id: "jira",
    type: "tool",
    label: "Jira",
    themed: false,
  },
  {
    id: "slack",
    type: "tool",
    label: "Slack",
    themed: false,
  },
  {
    id: "bit-bucket",
    type: "tool",
    label: "BitBucket",
    themed: true,
  },
  {
    id: "powershell",
    type: "tool",
    label: "Powershell",
    themed: true,
  },
];
